#!/usr/bin/env bash
# =============================================================================
# master.sh
# Bootstrap the Kubernetes control plane with kubeadm and publish join artifacts.
# Idempotent: skips kubeadm init when the cluster is already initialized.
# =============================================================================
set -euxo pipefail

LOG_TAG="[master]"
log() { echo "${LOG_TAG} $(date -u +'%Y-%m-%dT%H:%M:%SZ') $*"; }
err() { echo "${LOG_TAG} ERROR: $*" >&2; exit 1; }

export DEBIAN_FRONTEND=noninteractive

MASTER_IP="${MASTER_IP:-192.168.56.10}"
JOIN_COMMAND_FILE="${JOIN_COMMAND_FILE:-/vagrant/.cluster/join.sh}"
KUBECONFIG_FILE="${KUBECONFIG_FILE:-/vagrant/.cluster/admin.conf}"

# Pod CIDR compatible with Cilium (not used by kube-proxy when replaced)
POD_CIDR="${POD_CIDR:-10.244.0.0/16}"
SERVICE_CIDR="${SERVICE_CIDR:-10.96.0.0/12}"
CLUSTER_DIR="/vagrant/.cluster"

log "Starting control-plane bootstrap on $(hostname) (${MASTER_IP})"

mkdir -p "${CLUSTER_DIR}"
chmod 0777 "${CLUSTER_DIR}"

# -----------------------------------------------------------------------------
# Idempotency: detect existing cluster
# -----------------------------------------------------------------------------
ALREADY_INIT=0
if [[ -f /etc/kubernetes/admin.conf ]]; then
  log "Detected existing /etc/kubernetes/admin.conf — treating cluster as initialized"
  ALREADY_INIT=1
fi

if [[ "${ALREADY_INIT}" -eq 0 ]]; then
  log "Pulling control-plane images"
  kubeadm config images pull \
    --cri-socket=unix:///run/containerd/containerd.sock

  log "Running kubeadm init (skip kube-proxy for Cilium replacement)"
  # --skip-phases=addon/kube-proxy enables Cilium kube-proxy replacement
  kubeadm init \
    --apiserver-advertise-address="${MASTER_IP}" \
    --control-plane-endpoint="${MASTER_IP}" \
    --pod-network-cidr="${POD_CIDR}" \
    --service-cidr="${SERVICE_CIDR}" \
    --cri-socket=unix:///run/containerd/containerd.sock \
    --skip-phases=addon/kube-proxy \
    --upload-certs \
    | tee "${CLUSTER_DIR}/kubeadm-init.log"
else
  log "Skipping kubeadm init (already initialized)"
fi

# -----------------------------------------------------------------------------
# Configure kubectl for root and devops
# -----------------------------------------------------------------------------
configure_kubeconfig() {
  local user_name="$1"
  local home_dir="$2"

  log "Configuring kubectl for ${user_name}"
  install -d -m 0755 -o "${user_name}" -g "${user_name}" "${home_dir}/.kube"
  install -m 0644 -o "${user_name}" -g "${user_name}" \
    /etc/kubernetes/admin.conf "${home_dir}/.kube/config"

  # Bash completion helper (idempotent)
  local bashrc="${home_dir}/.bashrc"
  if [[ -f "${bashrc}" ]] && ! grep -q 'kubectl completion bash' "${bashrc}"; then
    {
      echo ''
      echo '# kubectl completion'
      echo "source <(kubectl completion bash)"
      echo 'alias k=kubectl'
      echo 'complete -o default -F __start_kubectl k'
    } >> "${bashrc}"
    chown "${user_name}:${user_name}" "${bashrc}"
  fi
}

[[ -f /etc/kubernetes/admin.conf ]] || err "admin.conf missing after init"

configure_kubeconfig "root" "/root"
if id -u devops >/dev/null 2>&1; then
  configure_kubeconfig "devops" "$(getent passwd devops | cut -d: -f6)"
fi

export KUBECONFIG=/etc/kubernetes/admin.conf

# -----------------------------------------------------------------------------
# Persist kubeconfig and join command for workers / host
# -----------------------------------------------------------------------------
log "Saving kubeconfig to ${KUBECONFIG_FILE}"
install -m 0644 /etc/kubernetes/admin.conf "${KUBECONFIG_FILE}"

log "Generating worker join command"
# Token create is safe to re-run; refresh join script each provision
JOIN_CMD="$(kubeadm token create --print-join-command)"
cat > "${JOIN_COMMAND_FILE}" <<EOF
#!/usr/bin/env bash
set -euxo pipefail
# Auto-generated by master.sh — do not edit manually
${JOIN_CMD} --cri-socket=unix:///run/containerd/containerd.sock
EOF
chmod 0755 "${JOIN_COMMAND_FILE}"

# Also keep a plain-text copy for operators
echo "${JOIN_CMD}" > "${CLUSTER_DIR}/join-command.txt"
chmod 0644 "${CLUSTER_DIR}/join-command.txt"

log "Waiting for API server to become ready"
for i in $(seq 1 60); do
  if kubectl get --raw='/readyz' >/dev/null 2>&1; then
    log "API server is ready"
    break
  fi
  if [[ "${i}" -eq 60 ]]; then
    err "API server did not become ready in time"
  fi
  sleep 5
done

kubectl get nodes -o wide || true
log "Control-plane bootstrap completed successfully"
